# Global configuration options. These can also be set on each task.
queue_ahead: 360 # Number of minutes to queue jobs into the future

# Runs once every 2 minutes
# job will not run if 23 hours passes (server downtime) before the job is actually run
RefreshWidgetsData:
  class: "RefreshWidgetsWorker"
  every: "1.minute"
  expires_after: "5.minutes"

NotifyGolfGeniusData:
  class: "NotifyGolfGeniusWorker"
  every: "1.day"
  at: "16:00"
  expires_after: "23.hours"
